#!/usr/bin/env python3
"""Generate src/Jevstral/Quantization/QuantGrids.g.cs.

The i-quant families (IQ1/IQ2/IQ3) do not store weights directly: each group of
4 or 8 weights is an index into a fixed codebook, and only the index, a sign
mask and a scale are written to the file. Those codebooks are constants of the
format, several thousand entries wide, and a single wrong entry corrupts a
tensor in a way that is very hard to trace back from a bad logit.

Rather than transcribe them by hand, this script derives them from the
reference `gguf` Python package (the same tables llama.cpp ships in
ggml-common.h) and emits them as base64 blobs. Re-run it after a `gguf` upgrade;
the C# dequantizer tests compare against the same package at test time, so a
drift between the two shows up as a test failure rather than silent corruption.

Usage:  python3 tools/gen_quant_grids.py [output.cs]
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

import numpy as np
from gguf.quants import IQ1_S, IQ2_S, IQ2_XS, IQ2_XXS, IQ3_S, IQ3_XXS, IQ4_NL, MXFP4

OUT_DEFAULT = (
    Path(__file__).resolve().parent.parent
    / "src/Jevstral/Quantization/QuantGrids.g.cs"
)


def grid_bytes(cls) -> tuple[bytes, tuple[int, int]]:
    """Codebook of `cls` as one signed byte per entry, row-major."""
    cls.init_grid()
    assert cls.grid is not None, cls.__name__
    flat = cls.grid.reshape(-1).astype(np.int64)
    lo, hi = int(flat.min()), int(flat.max())
    assert -128 <= lo and hi <= 127, f"{cls.__name__} grid does not fit in sbyte: [{lo},{hi}]"
    return flat.astype(np.int8).tobytes(), cls.grid_shape


def wrap(b64: str, indent: str = "        ", width: int = 96) -> str:
    lines = [b64[i : i + width] for i in range(0, len(b64), width)]
    return ("\n" + indent + "+ ").join(f'"{line}"' for line in lines)


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DEFAULT

    grids = {
        "Iq2Xxs": IQ2_XXS,
        "Iq2Xs": IQ2_XS,
        "Iq2S": IQ2_S,
        "Iq3Xxs": IQ3_XXS,
        "Iq3S": IQ3_S,
        "Iq1S": IQ1_S,
    }

    parts: list[str] = []
    for name, cls in grids.items():
        blob, shape = grid_bytes(cls)
        parts.append(
            f"""
    /// <summary>{cls.qtype.name} codebook: {shape[0]} entries x {shape[1]} values.</summary>
    public static ReadOnlySpan<sbyte> {name}Grid => _{name.lower()}Grid;

    private static readonly sbyte[] _{name.lower()}Grid = Decode(
{wrap(base64.b64encode(blob).decode())});
"""
        )

    ksigns = np.frombuffer(IQ2_XXS.ksigns, dtype=np.uint8)
    assert ksigns.size == 128

    iq4nl = np.array(IQ4_NL.kvalues, dtype=np.int8)
    mxfp4 = np.array(MXFP4.kvalues, dtype=np.int8)

    body = "".join(parts)

    text = f"""// <auto-generated>
// Generated by tools/gen_quant_grids.py from the reference `gguf` Python package
// (the same tables as ggml-common.h). Do not edit by hand — regenerate instead.
//
// Each grid entry is one signed byte. A grid of shape (N, K) is stored row-major:
// entry i occupies [i*K, i*K + K).
// </auto-generated>
namespace Jevstral.Quantization;

internal static class QuantGrids
{{
    /// <summary>
    /// Sign lookup shared by IQ2_XXS / IQ2_XS / IQ3_XXS: index by the 7-bit sign
    /// field to get 8 sign bits whose parity makes the full 8-bit mask.
    /// </summary>
    public static ReadOnlySpan<byte> KSigns => [{", ".join(str(int(v)) for v in ksigns)}];

    /// <summary>IQ4_NL / IQ4_XS non-linear 16-value codebook.</summary>
    public static ReadOnlySpan<sbyte> Iq4NlValues => [{", ".join(str(int(v)) for v in iq4nl)}];

    /// <summary>MXFP4 E2M1 codebook, doubled (OCP microscaling v1.0).</summary>
    public static ReadOnlySpan<sbyte> Mxfp4Values => [{", ".join(str(int(v)) for v in mxfp4)}];
{body}
    private static sbyte[] Decode(string base64)
    {{
        byte[] raw = Convert.FromBase64String(base64);
        var result = new sbyte[raw.Length];
        Buffer.BlockCopy(raw, 0, result, 0, raw.Length);
        return result;
    }}
}}
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
